/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSpendingIndexRouteImport } from './routes/_app/spending/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSavingsIndexRouteImport } from './routes/_app/savings/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppReconciliationIndexRouteImport } from './routes/_app/reconciliation/index'
import { Route as AppLedgerIndexRouteImport } from './routes/_app/ledger/index'
import { Route as AppCryptoIndexRouteImport } from './routes/_app/crypto/index'
import { Route as AppBudgetsIndexRouteImport } from './routes/_app/budgets/index'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets/index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSettingsRulesRouteImport } from './routes/_app/settings/rules'
import { Route as AppSettingsMappingsRouteImport } from './routes/_app/settings/mappings'
import { Route as AppSettingsConnectionsRouteImport } from './routes/_app/settings/connections'
import { Route as AppSettingsBooksRouteImport } from './routes/_app/settings/books'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings/audit'
import { Route as AppReportsTrialBalanceRouteImport } from './routes/_app/reports/trial-balance'
import { Route as AppReportsTaxLossHarvestingRouteImport } from './routes/_app/reports/tax-loss-harvesting'
import { Route as AppReportsScheduleCRouteImport } from './routes/_app/reports/schedule-c'
import { Route as AppReportsQuarterlyEstimatesRouteImport } from './routes/_app/reports/quarterly-estimates'
import { Route as AppReportsProfitAndLossRouteImport } from './routes/_app/reports/profit-and-loss'
import { Route as AppReportsGeneralLedgerRouteImport } from './routes/_app/reports/general-ledger'
import { Route as AppReportsForm8949RouteImport } from './routes/_app/reports/form-8949'
import { Route as AppReportsCashFlowRouteImport } from './routes/_app/reports/cash-flow'
import { Route as AppReportsBalanceSheetRouteImport } from './routes/_app/reports/balance-sheet'
import { Route as AppLedgerNewRouteImport } from './routes/_app/ledger/new'
import { Route as AppAssetsAssetIdRouteImport } from './routes/_app/assets/$assetId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSpendingIndexRoute = AppSpendingIndexRouteImport.update({
  id: '/spending/',
  path: '/spending/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsIndexRoute = AppSavingsIndexRouteImport.update({
  id: '/savings/',
  path: '/savings/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReconciliationIndexRoute = AppReconciliationIndexRouteImport.update({
  id: '/reconciliation/',
  path: '/reconciliation/',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerIndexRoute = AppLedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => AppRoute,
} as any)
const AppCryptoIndexRoute = AppCryptoIndexRouteImport.update({
  id: '/crypto/',
  path: '/crypto/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsIndexRoute = AppBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRulesRoute = AppSettingsRulesRouteImport.update({
  id: '/settings/rules',
  path: '/settings/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMappingsRoute = AppSettingsMappingsRouteImport.update({
  id: '/settings/mappings',
  path: '/settings/mappings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsConnectionsRoute = AppSettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBooksRoute = AppSettingsBooksRouteImport.update({
  id: '/settings/books',
  path: '/settings/books',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsTrialBalanceRoute = AppReportsTrialBalanceRouteImport.update({
  id: '/reports/trial-balance',
  path: '/reports/trial-balance',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsTaxLossHarvestingRoute =
  AppReportsTaxLossHarvestingRouteImport.update({
    id: '/reports/tax-loss-harvesting',
    path: '/reports/tax-loss-harvesting',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsScheduleCRoute = AppReportsScheduleCRouteImport.update({
  id: '/reports/schedule-c',
  path: '/reports/schedule-c',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsQuarterlyEstimatesRoute =
  AppReportsQuarterlyEstimatesRouteImport.update({
    id: '/reports/quarterly-estimates',
    path: '/reports/quarterly-estimates',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsProfitAndLossRoute = AppReportsProfitAndLossRouteImport.update({
  id: '/reports/profit-and-loss',
  path: '/reports/profit-and-loss',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsGeneralLedgerRoute = AppReportsGeneralLedgerRouteImport.update({
  id: '/reports/general-ledger',
  path: '/reports/general-ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsForm8949Route = AppReportsForm8949RouteImport.update({
  id: '/reports/form-8949',
  path: '/reports/form-8949',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCashFlowRoute = AppReportsCashFlowRouteImport.update({
  id: '/reports/cash-flow',
  path: '/reports/cash-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsBalanceSheetRoute = AppReportsBalanceSheetRouteImport.update({
  id: '/reports/balance-sheet',
  path: '/reports/balance-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerNewRoute = AppLedgerNewRouteImport.update({
  id: '/ledger/new',
  path: '/ledger/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsAssetIdRoute = AppAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/ledger/new': typeof AppLedgerNewRoute
  '/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/reports/cash-flow': typeof AppReportsCashFlowRoute
  '/reports/form-8949': typeof AppReportsForm8949Route
  '/reports/general-ledger': typeof AppReportsGeneralLedgerRoute
  '/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/reports/quarterly-estimates': typeof AppReportsQuarterlyEstimatesRoute
  '/reports/schedule-c': typeof AppReportsScheduleCRoute
  '/reports/tax-loss-harvesting': typeof AppReportsTaxLossHarvestingRoute
  '/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/books': typeof AppSettingsBooksRoute
  '/settings/connections': typeof AppSettingsConnectionsRoute
  '/settings/mappings': typeof AppSettingsMappingsRoute
  '/settings/rules': typeof AppSettingsRulesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/budgets/': typeof AppBudgetsIndexRoute
  '/crypto/': typeof AppCryptoIndexRoute
  '/ledger/': typeof AppLedgerIndexRoute
  '/reconciliation/': typeof AppReconciliationIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/savings/': typeof AppSavingsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/spending/': typeof AppSpendingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/ledger/new': typeof AppLedgerNewRoute
  '/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/reports/cash-flow': typeof AppReportsCashFlowRoute
  '/reports/form-8949': typeof AppReportsForm8949Route
  '/reports/general-ledger': typeof AppReportsGeneralLedgerRoute
  '/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/reports/quarterly-estimates': typeof AppReportsQuarterlyEstimatesRoute
  '/reports/schedule-c': typeof AppReportsScheduleCRoute
  '/reports/tax-loss-harvesting': typeof AppReportsTaxLossHarvestingRoute
  '/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/books': typeof AppSettingsBooksRoute
  '/settings/connections': typeof AppSettingsConnectionsRoute
  '/settings/mappings': typeof AppSettingsMappingsRoute
  '/settings/rules': typeof AppSettingsRulesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/assets': typeof AppAssetsIndexRoute
  '/budgets': typeof AppBudgetsIndexRoute
  '/crypto': typeof AppCryptoIndexRoute
  '/ledger': typeof AppLedgerIndexRoute
  '/reconciliation': typeof AppReconciliationIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/savings': typeof AppSavingsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/spending': typeof AppSpendingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/_app/ledger/new': typeof AppLedgerNewRoute
  '/_app/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/_app/reports/cash-flow': typeof AppReportsCashFlowRoute
  '/_app/reports/form-8949': typeof AppReportsForm8949Route
  '/_app/reports/general-ledger': typeof AppReportsGeneralLedgerRoute
  '/_app/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/_app/reports/quarterly-estimates': typeof AppReportsQuarterlyEstimatesRoute
  '/_app/reports/schedule-c': typeof AppReportsScheduleCRoute
  '/_app/reports/tax-loss-harvesting': typeof AppReportsTaxLossHarvestingRoute
  '/_app/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/books': typeof AppSettingsBooksRoute
  '/_app/settings/connections': typeof AppSettingsConnectionsRoute
  '/_app/settings/mappings': typeof AppSettingsMappingsRoute
  '/_app/settings/rules': typeof AppSettingsRulesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/budgets/': typeof AppBudgetsIndexRoute
  '/_app/crypto/': typeof AppCryptoIndexRoute
  '/_app/ledger/': typeof AppLedgerIndexRoute
  '/_app/reconciliation/': typeof AppReconciliationIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/savings/': typeof AppSavingsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/spending/': typeof AppSpendingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/assets/$assetId'
    | '/ledger/new'
    | '/reports/balance-sheet'
    | '/reports/cash-flow'
    | '/reports/form-8949'
    | '/reports/general-ledger'
    | '/reports/profit-and-loss'
    | '/reports/quarterly-estimates'
    | '/reports/schedule-c'
    | '/reports/tax-loss-harvesting'
    | '/reports/trial-balance'
    | '/settings/audit'
    | '/settings/books'
    | '/settings/connections'
    | '/settings/mappings'
    | '/settings/rules'
    | '/api/auth/$'
    | '/accounts/'
    | '/assets/'
    | '/budgets/'
    | '/crypto/'
    | '/ledger/'
    | '/reconciliation/'
    | '/reports/'
    | '/savings/'
    | '/settings/'
    | '/spending/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/assets/$assetId'
    | '/ledger/new'
    | '/reports/balance-sheet'
    | '/reports/cash-flow'
    | '/reports/form-8949'
    | '/reports/general-ledger'
    | '/reports/profit-and-loss'
    | '/reports/quarterly-estimates'
    | '/reports/schedule-c'
    | '/reports/tax-loss-harvesting'
    | '/reports/trial-balance'
    | '/settings/audit'
    | '/settings/books'
    | '/settings/connections'
    | '/settings/mappings'
    | '/settings/rules'
    | '/api/auth/$'
    | '/accounts'
    | '/assets'
    | '/budgets'
    | '/crypto'
    | '/ledger'
    | '/reconciliation'
    | '/reports'
    | '/savings'
    | '/settings'
    | '/spending'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/dashboard'
    | '/_public/'
    | '/_app/assets/$assetId'
    | '/_app/ledger/new'
    | '/_app/reports/balance-sheet'
    | '/_app/reports/cash-flow'
    | '/_app/reports/form-8949'
    | '/_app/reports/general-ledger'
    | '/_app/reports/profit-and-loss'
    | '/_app/reports/quarterly-estimates'
    | '/_app/reports/schedule-c'
    | '/_app/reports/tax-loss-harvesting'
    | '/_app/reports/trial-balance'
    | '/_app/settings/audit'
    | '/_app/settings/books'
    | '/_app/settings/connections'
    | '/_app/settings/mappings'
    | '/_app/settings/rules'
    | '/api/auth/$'
    | '/_app/accounts/'
    | '/_app/assets/'
    | '/_app/budgets/'
    | '/_app/crypto/'
    | '/_app/ledger/'
    | '/_app/reconciliation/'
    | '/_app/reports/'
    | '/_app/savings/'
    | '/_app/settings/'
    | '/_app/spending/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spending/': {
      id: '/_app/spending/'
      path: '/spending'
      fullPath: '/spending/'
      preLoaderRoute: typeof AppSpendingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/savings/': {
      id: '/_app/savings/'
      path: '/savings'
      fullPath: '/savings/'
      preLoaderRoute: typeof AppSavingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reconciliation/': {
      id: '/_app/reconciliation/'
      path: '/reconciliation'
      fullPath: '/reconciliation/'
      preLoaderRoute: typeof AppReconciliationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger/': {
      id: '/_app/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof AppLedgerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crypto/': {
      id: '/_app/crypto/'
      path: '/crypto'
      fullPath: '/crypto/'
      preLoaderRoute: typeof AppCryptoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/': {
      id: '/_app/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof AppBudgetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/rules': {
      id: '/_app/settings/rules'
      path: '/settings/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof AppSettingsRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/mappings': {
      id: '/_app/settings/mappings'
      path: '/settings/mappings'
      fullPath: '/settings/mappings'
      preLoaderRoute: typeof AppSettingsMappingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/connections': {
      id: '/_app/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AppSettingsConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/books': {
      id: '/_app/settings/books'
      path: '/settings/books'
      fullPath: '/settings/books'
      preLoaderRoute: typeof AppSettingsBooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/trial-balance': {
      id: '/_app/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AppReportsTrialBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/tax-loss-harvesting': {
      id: '/_app/reports/tax-loss-harvesting'
      path: '/reports/tax-loss-harvesting'
      fullPath: '/reports/tax-loss-harvesting'
      preLoaderRoute: typeof AppReportsTaxLossHarvestingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/schedule-c': {
      id: '/_app/reports/schedule-c'
      path: '/reports/schedule-c'
      fullPath: '/reports/schedule-c'
      preLoaderRoute: typeof AppReportsScheduleCRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/quarterly-estimates': {
      id: '/_app/reports/quarterly-estimates'
      path: '/reports/quarterly-estimates'
      fullPath: '/reports/quarterly-estimates'
      preLoaderRoute: typeof AppReportsQuarterlyEstimatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/profit-and-loss': {
      id: '/_app/reports/profit-and-loss'
      path: '/reports/profit-and-loss'
      fullPath: '/reports/profit-and-loss'
      preLoaderRoute: typeof AppReportsProfitAndLossRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/general-ledger': {
      id: '/_app/reports/general-ledger'
      path: '/reports/general-ledger'
      fullPath: '/reports/general-ledger'
      preLoaderRoute: typeof AppReportsGeneralLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/form-8949': {
      id: '/_app/reports/form-8949'
      path: '/reports/form-8949'
      fullPath: '/reports/form-8949'
      preLoaderRoute: typeof AppReportsForm8949RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/cash-flow': {
      id: '/_app/reports/cash-flow'
      path: '/reports/cash-flow'
      fullPath: '/reports/cash-flow'
      preLoaderRoute: typeof AppReportsCashFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/balance-sheet': {
      id: '/_app/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof AppReportsBalanceSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger/new': {
      id: '/_app/ledger/new'
      path: '/ledger/new'
      fullPath: '/ledger/new'
      preLoaderRoute: typeof AppLedgerNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/$assetId': {
      id: '/_app/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AppAssetsAssetIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAssetsAssetIdRoute: typeof AppAssetsAssetIdRoute
  AppLedgerNewRoute: typeof AppLedgerNewRoute
  AppReportsBalanceSheetRoute: typeof AppReportsBalanceSheetRoute
  AppReportsCashFlowRoute: typeof AppReportsCashFlowRoute
  AppReportsForm8949Route: typeof AppReportsForm8949Route
  AppReportsGeneralLedgerRoute: typeof AppReportsGeneralLedgerRoute
  AppReportsProfitAndLossRoute: typeof AppReportsProfitAndLossRoute
  AppReportsQuarterlyEstimatesRoute: typeof AppReportsQuarterlyEstimatesRoute
  AppReportsScheduleCRoute: typeof AppReportsScheduleCRoute
  AppReportsTaxLossHarvestingRoute: typeof AppReportsTaxLossHarvestingRoute
  AppReportsTrialBalanceRoute: typeof AppReportsTrialBalanceRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsBooksRoute: typeof AppSettingsBooksRoute
  AppSettingsConnectionsRoute: typeof AppSettingsConnectionsRoute
  AppSettingsMappingsRoute: typeof AppSettingsMappingsRoute
  AppSettingsRulesRoute: typeof AppSettingsRulesRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppBudgetsIndexRoute: typeof AppBudgetsIndexRoute
  AppCryptoIndexRoute: typeof AppCryptoIndexRoute
  AppLedgerIndexRoute: typeof AppLedgerIndexRoute
  AppReconciliationIndexRoute: typeof AppReconciliationIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSavingsIndexRoute: typeof AppSavingsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSpendingIndexRoute: typeof AppSpendingIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAssetsAssetIdRoute: AppAssetsAssetIdRoute,
  AppLedgerNewRoute: AppLedgerNewRoute,
  AppReportsBalanceSheetRoute: AppReportsBalanceSheetRoute,
  AppReportsCashFlowRoute: AppReportsCashFlowRoute,
  AppReportsForm8949Route: AppReportsForm8949Route,
  AppReportsGeneralLedgerRoute: AppReportsGeneralLedgerRoute,
  AppReportsProfitAndLossRoute: AppReportsProfitAndLossRoute,
  AppReportsQuarterlyEstimatesRoute: AppReportsQuarterlyEstimatesRoute,
  AppReportsScheduleCRoute: AppReportsScheduleCRoute,
  AppReportsTaxLossHarvestingRoute: AppReportsTaxLossHarvestingRoute,
  AppReportsTrialBalanceRoute: AppReportsTrialBalanceRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsBooksRoute: AppSettingsBooksRoute,
  AppSettingsConnectionsRoute: AppSettingsConnectionsRoute,
  AppSettingsMappingsRoute: AppSettingsMappingsRoute,
  AppSettingsRulesRoute: AppSettingsRulesRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppBudgetsIndexRoute: AppBudgetsIndexRoute,
  AppCryptoIndexRoute: AppCryptoIndexRoute,
  AppLedgerIndexRoute: AppLedgerIndexRoute,
  AppReconciliationIndexRoute: AppReconciliationIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSavingsIndexRoute: AppSavingsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSpendingIndexRoute: AppSpendingIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
